# Generated by Django 4.1 on 2022-08-07 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calificacion_acordeonero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Tipo')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total', models.IntegerField(verbose_name='Total')),
                ('juez', models.CharField(max_length=100, verbose_name='Juez')),
            ],
        ),
        migrations.CreateModel(
            name='calificacion_cancion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cancion', models.CharField(max_length=100, verbose_name='Tipo')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total', models.IntegerField(verbose_name='Total')),
                ('juez', models.CharField(max_length=100, verbose_name='Juez')),
            ],
        ),
        migrations.CreateModel(
            name='calificacion_piqueria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Tipo')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total', models.IntegerField(verbose_name='Total')),
                ('juez', models.CharField(max_length=100, verbose_name='Juez')),
            ],
        ),
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='participantes',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False, verbose_name='Cedula')),
                ('nombre', models.TextField(max_length=100, verbose_name='Nombre')),
                ('cancion', models.TextField(max_length=100, verbose_name='Nombre de la cancion')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concursos.categoria', verbose_name='Categoria')),
            ],
        ),
    ]
