# Generated by Django 4.1 on 2022-08-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0002_alter_participantes_cancion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion_acordeonero',
            name='juez',
        ),
        migrations.RemoveField(
            model_name='calificacion_acordeonero',
            name='total',
        ),
        migrations.RemoveField(
            model_name='calificacion_cancion',
            name='juez',
        ),
        migrations.RemoveField(
            model_name='calificacion_cancion',
            name='total',
        ),
        migrations.RemoveField(
            model_name='calificacion_piqueria',
            name='juez',
        ),
        migrations.RemoveField(
            model_name='calificacion_piqueria',
            name='total',
        ),
        migrations.AddField(
            model_name='calificacion_acordeonero',
            name='total_1',
            field=models.IntegerField(default=0, verbose_name='Juez 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificacion_acordeonero',
            name='total_2',
            field=models.IntegerField(default=0, verbose_name='Juez 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificacion_acordeonero',
            name='total_3',
            field=models.IntegerField(default=0, verbose_name='Juez 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificacion_cancion',
            name='total_1',
            field=models.IntegerField(default=0, verbose_name='Juez 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificacion_cancion',
            name='total_2',
            field=models.IntegerField(default=0, verbose_name='Juez 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificacion_cancion',
            name='total_3',
            field=models.IntegerField(default=0, verbose_name='Juez 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificacion_piqueria',
            name='total_1',
            field=models.IntegerField(default=0, verbose_name='Juez 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificacion_piqueria',
            name='total_2',
            field=models.IntegerField(default=0, verbose_name='Juez 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificacion_piqueria',
            name='total_3',
            field=models.IntegerField(default=0, verbose_name='Juez 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participantes',
            name='cancion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la cancion si aplica'),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='categoria',
            field=models.CharField(choices=[('CANCION INEDITA', 'Cancion Inedita'), ('ACORDEONERO', 'Acordeonero'), ('PIQUERIA', 'Piqueria')], max_length=100, verbose_name='Categoria'),
        ),
    ]
