# Generated by Django 4.1 on 2022-08-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0003_remove_calificacion_acordeonero_juez_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='concursante',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False, verbose_name='Cedula')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cancion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de la cancion si aplica')),
                ('categoria', models.CharField(choices=[('CANCION INEDITA', 'Cancion Inedita'), ('ACORDEONERO', 'Acordeonero'), ('PIQUERIA', 'Piqueria')], max_length=100, verbose_name='Categoria')),
            ],
        ),
    ]
