# Generated by Django 4.1 on 2022-08-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0004_concursante'),
    ]

    operations = [
        migrations.AddField(
            model_name='concursante',
            name='puntaje',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='Puntaje'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concursante',
            name='ronda',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ronda'),
        ),
        migrations.AlterField(
            model_name='concursante',
            name='categoria',
            field=models.CharField(choices=[('CANCION INEDITA', 'Cancion Inedita'), ('ACORDEONERO', 'Acordeonero'), ('PIQUERIA', 'Piqueria'), ('PIQUERIA INFANTIL', 'Piqueria Infantil')], max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='participantes',
            name='categoria',
            field=models.CharField(choices=[('CANCION INEDITA', 'Cancion Inedita'), ('ACORDEONERO', 'Acordeonero'), ('PIQUERIA', 'Piqueria'), ('PIQUERIA INFANTIL', 'Piqueria Infantil')], max_length=100, verbose_name='Categoria'),
        ),
    ]
