# Generated by Django 4.1 on 2022-08-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0005_concursante_puntaje_concursante_ronda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concursante',
            name='puntaje',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Total'),
        ),
    ]
