# Generated by Django 4.1 on 2022-08-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0007_alter_concursante_puntaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion_acordeonero',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='calificacion_acordeonero',
            name='id',
        ),
        migrations.RemoveField(
            model_name='calificacion_acordeonero',
            name='total_1',
        ),
        migrations.RemoveField(
            model_name='calificacion_acordeonero',
            name='total_2',
        ),
        migrations.RemoveField(
            model_name='calificacion_acordeonero',
            name='total_3',
        ),
        migrations.AddField(
            model_name='calificacion_acordeonero',
            name='cedula',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificacion_acordeonero',
            name='ronda',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ronda'),
        ),
        migrations.AddField(
            model_name='calificacion_acordeonero',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Puntaje'),
            preserve_default=False,
        ),
    ]
